services:
  mysql:
    image: mysql:latest
    container_name: webty-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webty_db
      MYSQL_USER: webty_user
      MYSQL_PASSWORD: webty
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      - webty-network
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: webty-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - webty-network
    volumes:
      - redis_data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: webty-elasticsearch
    networks:
      - webty-network
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    container_name: webty-kibana
    networks:
      - webty-network
    ports:
      - "5601:5601"
    restart: unless-stopped
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://webty-elasticsearch:9200

networks:
  webty-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  elasticsearch_data:
    driver: local
